apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    gitlab.com/micro-services: ${{values.destination.category_name + "/" + values.destination.sub_category_name}}
    gitlab.com/project-id: ${{values.destination.gitlab_pid}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
